# Generated by Django 5.1.3 on 2024-12-05 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccsds_cdm_version', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField()),
                ('originator', models.CharField(max_length=50)),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('tca', models.DateTimeField()),
                ('miss_distance', models.FloatField()),
                ('sat1_object', models.CharField(max_length=50)),
                ('sat1_object_designator', models.CharField(max_length=50)),
                ('sat1_maneuverable', models.CharField(max_length=3)),
                ('sat1_x', models.FloatField()),
                ('sat1_y', models.FloatField()),
                ('sat1_z', models.FloatField()),
                ('sat1_x_dot', models.FloatField()),
                ('sat1_y_dot', models.FloatField()),
                ('sat1_z_dot', models.FloatField()),
                ('sat1_cov_rr', models.FloatField(blank=True, null=True)),
                ('sat1_cov_rt', models.FloatField(blank=True, null=True)),
                ('sat1_cov_rn', models.FloatField(blank=True, null=True)),
                ('sat1_cov_tr', models.FloatField(blank=True, null=True)),
                ('sat1_cov_tt', models.FloatField(blank=True, null=True)),
                ('sat1_cov_tn', models.FloatField(blank=True, null=True)),
                ('sat1_cov_nr', models.FloatField(blank=True, null=True)),
                ('sat1_cov_nt', models.FloatField(blank=True, null=True)),
                ('sat1_cov_nn', models.FloatField(blank=True, null=True)),
                ('sat2_object', models.CharField(max_length=50)),
                ('sat2_object_designator', models.CharField(max_length=50)),
                ('sat2_maneuverable', models.CharField(max_length=3)),
                ('sat2_x', models.FloatField()),
                ('sat2_y', models.FloatField()),
                ('sat2_z', models.FloatField()),
                ('sat2_x_dot', models.FloatField()),
                ('sat2_y_dot', models.FloatField()),
                ('sat2_z_dot', models.FloatField()),
                ('sat2_cov_rr', models.FloatField(blank=True, null=True)),
                ('sat2_cov_rt', models.FloatField(blank=True, null=True)),
                ('sat2_cov_rn', models.FloatField(blank=True, null=True)),
                ('sat2_cov_tr', models.FloatField(blank=True, null=True)),
                ('sat2_cov_tt', models.FloatField(blank=True, null=True)),
                ('sat2_cov_tn', models.FloatField(blank=True, null=True)),
                ('sat2_cov_nr', models.FloatField(blank=True, null=True)),
                ('sat2_cov_nt', models.FloatField(blank=True, null=True)),
                ('sat2_cov_nn', models.FloatField(blank=True, null=True)),
                ('hard_body_radius', models.FloatField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conjunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('risk_factor', models.FloatField()),
                ('description', models.TextField()),
                ('sat1_object_designator', models.CharField(max_length=50)),
                ('sat2_object_designator', models.CharField(max_length=50)),
                ('cdm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjunctions', to='api.cdm')),
            ],
        ),
        migrations.CreateModel(
            name='Collision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collision_date', models.DateTimeField()),
                ('risk_factor', models.FloatField()),
                ('sat1_object_designator', models.CharField(max_length=50)),
                ('sat2_object_designator', models.CharField(max_length=50)),
                ('conjunction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collisions', to='api.conjunction')),
            ],
        ),
        migrations.CreateModel(
            name='ProbabilityCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability_value', models.FloatField()),
                ('time_to_impact', models.DurationField()),
                ('conjuction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probability_calcs', to='api.conjunction')),
            ],
        ),
    ]
