# Generated by Django 5.1.3 on 2024-11-06 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('risk_factor', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=100)),
                ('collision_date', models.DateTimeField()),
                ('risk_factor', models.FloatField()),
                ('conjunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collisions', to='api.conjunction')),
            ],
        ),
        migrations.CreateModel(
            name='ProbabilityCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability_value', models.FloatField()),
                ('time_to_impact', models.DurationField()),
                ('collision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probability_calculations', to='api.collision')),
            ],
        ),
    ]
