# Generated by Django 5.1.3 on 2024-11-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cdm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjunction',
            name='satellite_id',
        ),
        migrations.RemoveField(
            model_name='probabilitycalc',
            name='collision',
        ),
        migrations.AddField(
            model_name='cdm',
            name='hard_body_radius',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat1_cov_nn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat1_cov_nr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat1_cov_nt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat1_cov_rn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat1_cov_rr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat1_cov_rt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat1_cov_tn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat1_cov_tr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat1_cov_tt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat2_cov_nn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat2_cov_nr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat2_cov_nt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat2_cov_rn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat2_cov_rr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat2_cov_rt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat2_cov_tn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat2_cov_tr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='sat2_cov_tt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conjunction',
            name='cdm',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='conjunctions', to='api.cdm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='probabilitycalc',
            name='conjuction',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='probability_calcs', to='api.conjunction'),
            preserve_default=False,
        ),
    ]
