# Generated by Django 5.1.3 on 2024-11-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_conjunction_satellite_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collision',
            old_name='conjunction',
            new_name='conjunction_id',
        ),
        migrations.RenameField(
            model_name='conjunction',
            old_name='cdm',
            new_name='cdm_id',
        ),
        migrations.RenameField(
            model_name='probabilitycalc',
            old_name='conjuction',
            new_name='conjuction_id',
        ),
        migrations.RemoveField(
            model_name='collision',
            name='satellite_id',
        ),
    ]
