# Generated by Django 5.1.3 on 2024-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_conjunction_collision_conjunction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collision',
            name='sat1_object_designator',
            field=models.CharField(default='UNKOWN_SAT_1', max_length=50),
        ),
        migrations.AddField(
            model_name='collision',
            name='sat2_object_designator',
            field=models.CharField(default='UKNOWN_SAT_2', max_length=50),
        ),
        migrations.AddField(
            model_name='conjunction',
            name='sat1_object_designator',
            field=models.CharField(default='UNKOWN_SAT_1', max_length=50),
        ),
        migrations.AddField(
            model_name='conjunction',
            name='sat2_object_designator',
            field=models.CharField(default='UKNOWN_SAT_2', max_length=50),
        ),
    ]
