# Generated by Django 5.1.3 on 2025-02-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_password_hash_cdm_privacy_user_groups_and_more'),
        ('api', '0004_rename_risk_factor_collision_probability_of_collision_and_more'),
    ]

    operations = [
    ]
