# Generated by Django 5.1.3 on 2024-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_collision_sat1_object_designator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collision',
            name='sat1_object_designator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='collision',
            name='sat2_object_designator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='conjunction',
            name='sat1_object_designator',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='conjunction',
            name='sat2_object_designator',
            field=models.CharField(max_length=50),
        ),
    ]
