# Generated by Django 5.1.3 on 2025-02-16 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='alert_threshold',
            field=models.FloatField(default=5.36104950954095e-09),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
