# Generated by Django 5.1.3 on 2025-02-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_organization_alert_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdm',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='cdms', to='api.organization'),
        ),
    ]
