# Generated by Django 5.1.3 on 2025-02-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cdm_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdm',
            name='organizations',
        ),
        migrations.AddField(
            model_name='organization',
            name='cdms',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='api.cdm'),
        ),
    ]
