# Generated by Django 5.1.3 on 2025-02-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_cdm_organizations_organization_cdms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_cdms',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='api.cdm'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='alert_threshold',
            field=models.FloatField(default=1e-09),
        ),
    ]
