# Generated by Django 5.1.3 on 2025-04-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_interested_cdms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
